### ISSUE TITLE
Vendor-keyframes get useless vendor-properties

### ISSUE THREAD

**Issue by igl** [tj/nib#229]
A simple animation:

    @keyframes myAnim
        0%
            transform rotate(0)
        ...

...generates keyframes with tons of useless properties

    @-moz-keyframes myAnim {
        0% {
            -webkit-transform: rotate(0);
            -moz-transform: rotate(0);
            -o-transform: rotate(0);
            -ms-transform: rotate(0);
            transform: rotate(0);
        }
        ...

`@-moz-keyframes` should only have `-moz-transform` as property. etc.

**Comment by tannerlinsley** [comment]
We should get this fixed.  This would greatly impact the output size for nzAnimate http://github.com/nozzle/nzAnimate.  Is this a stylus bug or a nib bug?

**Comment by igl** [comment]
Here is a fix:

    vendors = 'official'
    @keyframes myAnim
        0%
            transform rotate(0)


This should stop stylus from creating vendor prefixes and leave it up to nib.
See: http://stylus-lang.com/docs/keyframes.html#expansion

**Comment by igl** [comment]
I closed this with a workaround.
This could be included in nib.
