### ISSUE TITLE
display box

### ISSUE THREAD

**Issue by Charuru** [tj/nib#23]
I think display box would fit in well here.

http://compass-style.org/reference/compass/css3/box/
http://www.html5rocks.com/en/tutorials/flexbox/quick/#toc-center

**Comment by Vargentum** [comment]
Can I disable erasing 'display: -webkit-box' from output css? 
I'm using it for pure CSS multiline ellipsis. http://codepen.io/anon/pen/NPYzgw

**Comment by groenroos** [comment]
+1 to what Vargentum said.
