### ISSUE TITLE
vendor prefixes!

### ISSUE THREAD

**Issue by gollodev** [tj/nib#305]
add this line vendor-prefixes ?= webkit moz o ms official, only shows webkit...

**Comment by slang800** [comment]
I'm going to need a bit more info to reproduce that...

**Comment by gollodev** [comment]
button
	border-radius 2px

compiled...

button {
  -webkit-border-radius: 2px;
  border-radius: 2px;
}

should be add -moz- -o- prefixes no?

**Comment by slang800** [comment]
As far as I can tell, opera never had a prefix for border-radius, and FF hasn't needed one since 3.6. Actually, Chrome hasn't needed one since v4, so we probably shouldn’t even be adding the webkit prefix.

**Comment by netlemur** [comment]
Yes, the webkit prefix should be removed for border-radius.

**Comment by netlemur** [comment]
@slang800 in case that's something you guys wanna do, there's a PR for it now: #306
