### ISSUE TITLE
Error: unexpected "indent" inside normalize base file

### ISSUE THREAD

**Issue by jsainthilaire** [tj/nib#315]
This is the error I'm getting:

Potentially unhandled rejection [2] ParseError: /node_modules/nib/lib/nib/normalize/base.styl:5:5
1| // Based in Nicolas Gallagher's git.io/normalize
2| normalize-base()
3|   html // Prevent iOS text size adjust after orientation change.
4|     font-family sans-serif
5|     -ms-text-size-adjust 100%
10:11:28.437 ----------^
6|     -webkit-text-size-adjust 100%
7|   body
8|     margin 0
 
unexpected "indent"

**Comment by drewloomer** [comment]
I just started getting this too moments ago. Hrm...

**Comment by neochrome** [comment]
I get the same error.
I'm on version 1.1.0

**Comment by drewloomer** [comment]
Looks to be an issue since Stylus was bumped to `0.52.1`. Installing `0.52.0` fixed the issue for me. Going to investigate what has changed...

**Comment by drewloomer** [comment]
[Looks like this is the commit that breaks nib.](https://github.com/stylus/stylus/commit/ca3de2f98fc61442d582be620a53598e98bcf17d) I need to investigate further to see if this is something nib should respond to or if it's a bug with Stylus.

**Comment by drewloomer** [comment]
Sorry for the comment vomit, but it seems that Stylus commit breaks comments at the end of a line. So it's obviously a Stylus issue and not nib. [I've opened an issue](https://github.com/stylus/stylus/issues/1996).

**Comment by jsainthilaire** [comment]
I was on version 1.1.0 then downgrade it to version 1.0.4, but I've been using version 1.1.0 since june and no problem until today.

**Comment by drewloomer** [comment]
@jsainthilaire That's because they just pushed `0.52.1` of Stylus about 3 hours ago. There is a fix coming and you can track progress [here](https://github.com/stylus/stylus/issues/1995).

**Comment by jsainthilaire** [comment]
Thanks a lot @drewloomer!

**Comment by parrish** [comment]
By the way, that's fixed now in [0.52.2](https://github.com/stylus/stylus/releases/tag/0.52.2)

**Comment by mciccarelli** [comment]
I've added the following to composer.php (before gulp build task) as a workaround until a patch is available:
```cd node_modules/gulp-stylus/
npm install stylus@0.52.0```

**Comment by jsainthilaire** [comment]
They release version 0.52.2, is working now. Thank you all.
