### ISSUE TITLE
Any plans for maintenance?

### ISSUE THREAD

**Issue by jmeas** [tj/nib#325]
I see there hasn't been much work this year, and there are many open issues. Is there plan to support the project going forward? If not, it might make sense to add a note to the README so that folks know what they're getting into.

**Comment by seleckis** [comment]
![tumblr_n70jg16yna1qhc150o1_1280](https://cloud.githubusercontent.com/assets/988504/15541323/a33296c2-2294-11e6-8717-4d9647981dea.gif)

**Comment by seleckis** [comment]
I think this is because of PostCSS. It just replaces a lot of mixins of nib.

**Comment by jmeas** [comment]
Makes sense, @seleckis . I never tried that out since nib had me covered. But lately it's just been disappointing me with these bugs I'm running into. Time to switch, I suppose! ✌️

**Comment by slang800** [comment]
I plan to continue supporting this because I use it in several of my projects, I just haven't had much time to work on it... Though I'm happy to take PRs if there's anything you'd like to add!

**Comment by seleckis** [comment]
@slang800 so, what do you think about to remove old mixins which could be replaced by PostCSS Autoprefixer (which is mush more popular now) and make an accent on other useful mixins?

**Comment by slang800** [comment]
I'm not sure about PostCSS (haven't used it enough), but I'd definitely like to handle vendor prefixing with Autoprefixer (see: #223)

**Comment by seleckis** [comment]
Autoprefixer is now provided as a plugin of PostCSS. So you don't need to use it as a part of nib, but just configure PostCSS in your builder (gulp/grunt etc.) to parse your CSS with that plugin.

Or use autoprefixer-stylus plugin if you use stylus native command: 
```
$ stylus < test.styl --use ../node_modules/autoprefixer-stylus --with "{ browsers: ['ie 7', 'ie 8'] }"
```
this is from documentation: http://stylus-lang.com/docs/executable.html

So there is no need to generate prefixes by nib. I suggest to remove this part.
